
services:
  postgres:
    image: postgres:15-alpine
    container_name: ecoride_postgres
    environment:
      POSTGRES_DB: ecoride_DB
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: postgrespasswordiZBvb9hNgKtoXxg1tV3hwxIm5gKsEOId
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ecoride_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpasswordiZBvb9hNgKtoXxg1tV3hwxIm5gKsEOId
      MONGO_INITDB_DATABASE: ecoride_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    
volumes:
  postgres_data:
  mongodb_data:
