<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260501205828 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_configurations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE bookings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, confirmation BOOLEAN NOT NULL, credits_used INT NOT NULL, status VARCHAR(255) NOT NULL, outcome_status VARCHAR(50) NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, payout_applied BOOLEAN NOT NULL, driver_credit_amount NUMERIC(10, 2) DEFAULT NULL, user_id INT DEFAULT NULL, trip_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7A853C35A76ED395 ON bookings (user_id)');
        $this->addSql('CREATE INDEX IDX_7A853C35A5BC2E0E ON bookings (trip_id)');
        $this->addSql('CREATE TABLE brands (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reviews (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment VARCHAR(1000) NOT NULL, rating INT NOT NULL, status VARCHAR(50) NOT NULL, moderated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, moderation_note VARCHAR(1000) DEFAULT NULL, user_id INT DEFAULT NULL, trip_id INT DEFAULT NULL, author_id INT DEFAULT NULL, moderated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6970EB0FA76ED395 ON reviews (user_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0FA5BC2E0E ON reviews (trip_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0FF675F31B ON reviews (author_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0F8EDA19B0 ON reviews (moderated_by_id)');
        $this->addSql('CREATE TABLE settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, property VARCHAR(50) NOT NULL, value VARCHAR(50) NOT NULL, app_configuration_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E545A0C5E7CDCC79 ON settings (app_configuration_id)');
        $this->addSql('CREATE TABLE trip_issues (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment VARCHAR(1000) NOT NULL, status VARCHAR(50) NOT NULL, resolution_note VARCHAR(1000) DEFAULT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trip_id INT NOT NULL, booking_id INT NOT NULL, participant_id INT DEFAULT NULL, driver_id INT DEFAULT NULL, resolved_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_35722429A5BC2E0E ON trip_issues (trip_id)');
        $this->addSql('CREATE INDEX IDX_357224293301C60 ON trip_issues (booking_id)');
        $this->addSql('CREATE INDEX IDX_357224299D1C3019 ON trip_issues (participant_id)');
        $this->addSql('CREATE INDEX IDX_35722429C3423909 ON trip_issues (driver_id)');
        $this->addSql('CREATE INDEX IDX_357224296713A32B ON trip_issues (resolved_by_id)');
        $this->addSql('CREATE TABLE trips (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, departure_date DATE NOT NULL, departure_time TIME(0) WITHOUT TIME ZONE NOT NULL, departure_location VARCHAR(50) NOT NULL, arrival_date DATE NOT NULL, arrival_time TIME(0) WITHOUT TIME ZONE NOT NULL, arrival_location VARCHAR(50) NOT NULL, available_seats INT NOT NULL, price_per_person NUMERIC(10, 2) NOT NULL, status VARCHAR(50) NOT NULL, driver_id INT DEFAULT NULL, vehicle_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA7370DAC3423909 ON trips (driver_id)');
        $this->addSql('CREATE INDEX IDX_AA7370DA545317D1 ON trips (vehicle_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, last_name VARCHAR(50) NOT NULL, first_name VARCHAR(50) NOT NULL, email VARCHAR(50) NOT NULL, password VARCHAR(255) NOT NULL, phone VARCHAR(50) NOT NULL, address VARCHAR(50) NOT NULL, birth_date DATE NOT NULL, photo BYTEA NOT NULL, username VARCHAR(50) NOT NULL, roles JSON NOT NULL, is_verified BOOLEAN NOT NULL, credit_balance NUMERIC(10, 2) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE vehicles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, model VARCHAR(50) NOT NULL, registration_number VARCHAR(50) NOT NULL, energy_type VARCHAR(50) NOT NULL, color VARCHAR(50) NOT NULL, first_registration_date DATE NOT NULL, places INT DEFAULT NULL, preferences JSON DEFAULT NULL, owner_id INT DEFAULT NULL, brand_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FCE69FA7E3C61F9 ON vehicles (owner_id)');
        $this->addSql('CREATE INDEX IDX_1FCE69FA44F5D008 ON vehicles (brand_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE bookings ADD CONSTRAINT FK_7A853C35A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bookings ADD CONSTRAINT FK_7A853C35A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trips (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F8EDA19B0 FOREIGN KEY (moderated_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE settings ADD CONSTRAINT FK_E545A0C5E7CDCC79 FOREIGN KEY (app_configuration_id) REFERENCES app_configurations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_issues ADD CONSTRAINT FK_35722429A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_issues ADD CONSTRAINT FK_357224293301C60 FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_issues ADD CONSTRAINT FK_357224299D1C3019 FOREIGN KEY (participant_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_issues ADD CONSTRAINT FK_35722429C3423909 FOREIGN KEY (driver_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_issues ADD CONSTRAINT FK_357224296713A32B FOREIGN KEY (resolved_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trips ADD CONSTRAINT FK_AA7370DAC3423909 FOREIGN KEY (driver_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trips ADD CONSTRAINT FK_AA7370DA545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicles ADD CONSTRAINT FK_1FCE69FA7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicles ADD CONSTRAINT FK_1FCE69FA44F5D008 FOREIGN KEY (brand_id) REFERENCES brands (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bookings DROP CONSTRAINT FK_7A853C35A76ED395');
        $this->addSql('ALTER TABLE bookings DROP CONSTRAINT FK_7A853C35A5BC2E0E');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0FA76ED395');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0FA5BC2E0E');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0FF675F31B');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0F8EDA19B0');
        $this->addSql('ALTER TABLE settings DROP CONSTRAINT FK_E545A0C5E7CDCC79');
        $this->addSql('ALTER TABLE trip_issues DROP CONSTRAINT FK_35722429A5BC2E0E');
        $this->addSql('ALTER TABLE trip_issues DROP CONSTRAINT FK_357224293301C60');
        $this->addSql('ALTER TABLE trip_issues DROP CONSTRAINT FK_357224299D1C3019');
        $this->addSql('ALTER TABLE trip_issues DROP CONSTRAINT FK_35722429C3423909');
        $this->addSql('ALTER TABLE trip_issues DROP CONSTRAINT FK_357224296713A32B');
        $this->addSql('ALTER TABLE trips DROP CONSTRAINT FK_AA7370DAC3423909');
        $this->addSql('ALTER TABLE trips DROP CONSTRAINT FK_AA7370DA545317D1');
        $this->addSql('ALTER TABLE vehicles DROP CONSTRAINT FK_1FCE69FA7E3C61F9');
        $this->addSql('ALTER TABLE vehicles DROP CONSTRAINT FK_1FCE69FA44F5D008');
        $this->addSql('DROP TABLE app_configurations');
        $this->addSql('DROP TABLE bookings');
        $this->addSql('DROP TABLE brands');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE trip_issues');
        $this->addSql('DROP TABLE trips');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE vehicles');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
