<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260405110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds trip completion workflow entities, statuses, review moderation, and payout tracking.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("UPDATE trips SET status = 'planned' WHERE status = 'planifie'");
        $this->addSql("UPDATE trips SET status = 'canceled' WHERE status = 'annule'");
        $this->addSql("UPDATE bookings SET status = 'confirmed' WHERE status = 'confirmee'");
        $this->addSql("UPDATE bookings SET status = 'refunded' WHERE status = 'remboursee'");
        $this->addSql("UPDATE bookings SET status = 'canceled' WHERE status = 'annulee'");
        $this->addSql("UPDATE reviews SET status = 'approved' WHERE status = 'VALIDE'");
        $this->addSql("UPDATE reviews SET status = 'pending' WHERE status = 'EN_ATTENTE'");
        $this->addSql("UPDATE reviews SET status = 'rejected' WHERE status = 'REFUSE'");

        $this->addSql("ALTER TABLE bookings ADD outcome_status VARCHAR(50) DEFAULT 'pending' NOT NULL");
        $this->addSql('ALTER TABLE bookings ADD responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE bookings ADD payout_applied BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE bookings ADD driver_credit_amount NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('UPDATE bookings b SET driver_credit_amount = GREATEST(t.price_per_person - 2.00, 0), payout_applied = CASE WHEN b.status = \'confirmed\' THEN true ELSE false END FROM trips t WHERE b.trip_id = t.id');

        $this->addSql('ALTER TABLE reviews ALTER rating TYPE INT USING rating::integer');
        $this->addSql('ALTER TABLE reviews ALTER comment TYPE VARCHAR(1000)');
        $this->addSql('ALTER TABLE reviews ADD trip_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reviews ADD author_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reviews ADD moderated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reviews ADD moderated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE reviews ADD moderation_note VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_REVIEWS_TRIP FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_REVIEWS_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_REVIEWS_MODERATED_BY FOREIGN KEY (moderated_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_REVIEWS_TRIP ON reviews (trip_id)');
        $this->addSql('CREATE INDEX IDX_REVIEWS_AUTHOR ON reviews (author_id)');
        $this->addSql('CREATE INDEX IDX_REVIEWS_MODERATED_BY ON reviews (moderated_by_id)');

        $this->addSql('CREATE TABLE trip_issues (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, trip_id INT NOT NULL, booking_id INT NOT NULL, participant_id INT DEFAULT NULL, driver_id INT DEFAULT NULL, resolved_by_id INT DEFAULT NULL, comment VARCHAR(1000) NOT NULL, status VARCHAR(50) NOT NULL, resolution_note VARCHAR(1000) DEFAULT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_TRIP_ISSUES_TRIP ON trip_issues (trip_id)');
        $this->addSql('CREATE INDEX IDX_TRIP_ISSUES_BOOKING ON trip_issues (booking_id)');
        $this->addSql('CREATE INDEX IDX_TRIP_ISSUES_PARTICIPANT ON trip_issues (participant_id)');
        $this->addSql('CREATE INDEX IDX_TRIP_ISSUES_DRIVER ON trip_issues (driver_id)');
        $this->addSql('CREATE INDEX IDX_TRIP_ISSUES_RESOLVED_BY ON trip_issues (resolved_by_id)');
        $this->addSql('ALTER TABLE trip_issues ADD CONSTRAINT FK_TRIP_ISSUES_TRIP FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trip_issues ADD CONSTRAINT FK_TRIP_ISSUES_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trip_issues ADD CONSTRAINT FK_TRIP_ISSUES_PARTICIPANT FOREIGN KEY (participant_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trip_issues ADD CONSTRAINT FK_TRIP_ISSUES_DRIVER FOREIGN KEY (driver_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trip_issues ADD CONSTRAINT FK_TRIP_ISSUES_RESOLVED_BY FOREIGN KEY (resolved_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_REVIEWS_TRIP');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_REVIEWS_AUTHOR');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_REVIEWS_MODERATED_BY');
        $this->addSql('DROP INDEX IDX_REVIEWS_TRIP');
        $this->addSql('DROP INDEX IDX_REVIEWS_AUTHOR');
        $this->addSql('DROP INDEX IDX_REVIEWS_MODERATED_BY');
        $this->addSql('ALTER TABLE reviews DROP trip_id');
        $this->addSql('ALTER TABLE reviews DROP author_id');
        $this->addSql('ALTER TABLE reviews DROP moderated_by_id');
        $this->addSql('ALTER TABLE reviews DROP moderated_at');
        $this->addSql('ALTER TABLE reviews DROP moderation_note');
        $this->addSql('ALTER TABLE reviews ALTER rating TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE reviews ALTER comment TYPE VARCHAR(50)');

        $this->addSql('DROP TABLE trip_issues');

        $this->addSql('ALTER TABLE bookings DROP outcome_status');
        $this->addSql('ALTER TABLE bookings DROP responded_at');
        $this->addSql('ALTER TABLE bookings DROP payout_applied');
        $this->addSql('ALTER TABLE bookings DROP driver_credit_amount');
    }
}
